# Generated by Django 5.0.4 on 2024-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course_code',
            field=models.CharField(max_length=5),
        ),
    ]
