# Generated by Django 5.1.6 on 2025-03-17 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unspecified'), (1, 'student'), (2, 'teacher'), (3, 'alumni'), (4, 'supervisor'), (5, 'admin'), (6, 'guest')], default=0),
        ),
        migrations.CreateModel(
            name='TempRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(blank=True, max_length=10, null=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('course_code', models.CharField(max_length=5)),
                ('middle_name', models.CharField(blank=True, max_length=64, null=True)),
                ('contact_no', models.CharField(max_length=20)),
                ('entry_year_from', models.IntegerField()),
                ('entry_year_to', models.IntegerField()),
                ('user_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='temp_record', to='onlinerequest.user_request')),
            ],
        ),
    ]
