# Generated by Django 5.1.6 on 2025-03-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0002_alter_user_user_type_temprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_request',
            name='date_release',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_request',
            name='schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
