# Generated by Django 5.1.6 on 2025-03-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0003_user_request_date_release_user_request_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'unspecified'), (1, 'student'), (2, 'faculty'), (3, 'alumni'), (5, 'admin'), (6, 'guest'), (7, 'authorized person')], default=0),
        ),
    ]
