# Generated by Django 4.2.11 on 2024-04-22 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0005_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_active',
        ),
    ]
