# Generated by Django 4.2.11 on 2024-04-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0009_profile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Records',
        ),
    ]
