# Generated by Django 4.2.11 on 2024-04-23 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0010_rename_student_records'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Records',
            new_name='Record',
        ),
    ]
