# Generated by Django 4.2.11 on 2024-04-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0011_rename_records_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_number',
        ),
    ]
