# Generated by Django 4.2.11 on 2024-04-23 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0012_remove_profile_student_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='course',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='lname',
            new_name='last_name',
        ),
    ]
