# Generated by Django 4.2.11 on 2024-04-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0015_requirement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requirement',
            name='no_of_files',
        ),
        migrations.AddField(
            model_name='requirement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
