# Generated by Django 4.2.11 on 2024-04-24 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0016_remove_requirement_no_of_files_requirement_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requirement',
            new_name='Document',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('no_of_files_required', models.PositiveIntegerField()),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='onlinerequest.document')),
            ],
        ),
    ]
