# Generated by Django 4.2.11 on 2024-04-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0017_rename_requirement_document_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='onlinerequest.document'),
        ),
    ]
