# Generated by Django 4.2.11 on 2024-04-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0018_alter_request_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='code',
        ),
    ]
