# Generated by Django 4.2.11 on 2024-04-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0019_remove_request_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='no_of_files_required',
            field=models.CharField(max_length=256),
        ),
    ]
