# Generated by Django 4.2.11 on 2024-04-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0020_alter_request_no_of_files_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='no_of_files_required',
            new_name='files_required',
        ),
    ]
