# Generated by Django 4.2.11 on 2024-04-29 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0021_rename_no_of_files_required_request_files_required'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='description',
        ),
    ]
