# Generated by Django 4.2.11 on 2024-04-29 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0022_rename_course_code_course_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='student_number',
            new_name='user_number',
        ),
    ]
