# Generated by Django 4.2.11 on 2024-04-30 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0026_remove_request_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinerequest.document'),
        ),
        migrations.CreateModel(
            name='User_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
                ('uploads', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='onlinerequest.request')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
