# Generated by Django 4.2.11 on 2024-05-01 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0027_alter_request_document_user_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_request',
            name='uploads',
            field=models.CharField(max_length=999),
        ),
    ]
