# Generated by Django 4.2.11 on 2024-05-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0032_alter_profile_contact_no_alter_record_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='contact_no',
            field=models.IntegerField(default='09667614313'),
        ),
    ]
