# Generated by Django 4.2.11 on 2024-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinerequest', '0034_alter_record_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='entry_year_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='entry_year_to',
            field=models.DateField(),
        ),
    ]
