SELECT * FROM TV_AUDITLOG WHERE CODE = 31 AND SUB_CODE = 2 ORDER BY TIME_STAMP DESC;

SELECT * FROM TV_AUDITTXT WHERE CODE = 31 AND SUB_CODE = 2

SELECT * FROM TV_AUDITLOG WHERE ADDITIONAL_INFORMATION LIKE '%ADDITIONAL_DATA:%' ORDER BY TIME_STAMP DESC;

SELECT * FROM TV_AUDITLOG WHERE USER_ID IS NULL;

SELECT * FROM TV_PRINTLOG WHERE FILE_SOURCE = 'ACTIVITY' ORDER BY DATE_PRINTED DESC;

UPDATE TV_PRINTLOG SET CASE_KEY = 12 WHERE PRINTLOG_KEY = 2268;
